# Generated by Django 5.0.3 on 2024-03-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'price',
                    models.DecimalField(decimal_places=2, max_digits=10)
                ),
                ('quantity', models.IntegerField()),
                (
                    'language',
                    models.CharField(
                        choices=[
                            ('aa', 'Afar'), ('ab', 'Abkhazian'),
                            ('af', 'Afrikaans'), ('ak', 'Akan'),
                            ('sq', 'Albanian'), ('am', 'Amharic'),
                            ('ar', 'Arabic'), ('an', 'Aragonese'),
                            ('hy', 'Armenian'), ('as', 'Assamese'),
                            ('av', 'Avaric'), ('ae', 'Avestan'),
                            ('ay', 'Aymara'), ('az', 'Azerbaijani'),
                            ('ba', 'Bashkir'), ('bm', 'Bambara'),
                            ('eu', 'Basque'), ('be', 'Belarusian'),
                            ('bn', 'Bengali'), ('bh', 'Bihari languages'),
                            ('bi', 'Bislama'), ('bo', 'Tibetan'),
                            ('bs', 'Bosnian'), ('br', 'Breton'),
                            ('bg', 'Bulgarian'), ('my', 'Burmese'),
                            ('ca', 'Catalan; Valencian'), ('cs', 'Czech'),
                            ('ch', 'Chamorro'), ('ce', 'Chechen'),
                            ('zh', 'Chinese'),
                            (
                                'cu',
                                'Church Slavic; Old Slavonic; Church Slavonic;         Old Bulgarian; Old Church Slavonic'
                            ), ('cv', 'Chuvash'), ('kw', 'Cornish'),
                            ('co', 'Corsican'),
                            ('cr', 'Cree'), ('cy', 'Welsh'), ('da', 'Danish'),
                            ('de', 'German'),
                            ('dv', 'Divehi; Dhivehi; Maldivian'),
                            ('nl', 'Dutch; Flemish'), ('dz', 'Dzongkha'),
                            ('el', 'Greek, Modern (1453-)'), ('en', 'English'),
                            ('eo', 'Esperanto'), ('et', 'Estonian'),
                            ('ee', 'Ewe'), ('fo', 'Faroese'),
                            ('fa', 'Persian'), ('fj', 'Fijian'),
                            ('fi', 'Finnish'), ('fr', 'French'),
                            ('fy', 'Western Frisian'), ('ff', 'Fulah'),
                            ('gd', 'Gaelic; Scottish Gaelic'), ('ga', 'Irish'),
                            ('gl', 'Galician'), ('gv', 'Manx'),
                            ('gn', 'Guarani'), ('gu', 'Gujarati'),
                            ('ht', 'Haitian; Haitian Creole'), ('ha', 'Hausa'),
                            ('he', 'Hebrew'), ('hz', 'Herero'),
                            ('hi', 'Hindi'), ('ho', 'Hiri Motu'),
                            ('hr', 'Croatian'), ('hu', 'Hungarian'),
                            ('ig', 'Igbo'), ('is', 'Icelandic'), ('io', 'Ido'),
                            ('ii', 'Sichuan Yi; Nuosu'), ('iu', 'Inuktitut'),
                            ('ie', 'Interlingue; Occidental'),
                            (
                                'ia',
                                'Interlingua (International Auxiliary Language Association)'
                            ), ('id', 'Indonesian'), ('ik', 'Inupiaq'),
                            ('it', 'Italian'), ('jv', 'Javanese'),
                            ('ja', 'Japanese'),
                            ('kl', 'Kalaallisut; Greenlandic'),
                            ('kn', 'Kannada'), ('ks', 'Kashmiri'),
                            ('ka', 'Georgian'), ('kk', 'Kazakh'),
                            ('km', 'Central Khmer'), ('ki', 'Kikuyu; Gikuyu'),
                            ('rw', 'Kinyarwanda'), ('ky', 'Kirghiz; Kyrgyz'),
                            ('kv', 'Komi'), ('kg', 'Kongo'), ('ko', 'Korean'),
                            ('kj', 'Kuanyama; Kwanyama'), ('ku', 'Kurdish'),
                            ('lo', 'Lao'), ('la', 'Latin'), ('lv', 'Latvian'),
                            ('li', 'Limburgan; Limburger; Limburgish'),
                            ('ln', 'Lingala'), ('lt', 'Lithuanian'),
                            ('lb', 'Luxembourgish; Letzeburgesch'),
                            ('lu', 'Luba-Katanga'), ('lg', 'Ganda'),
                            ('mk', 'Macedonian'), ('mh', 'Marshallese'),
                            ('ml', 'Malayalam'), ('mi', 'Maori'),
                            ('mr', 'Marathi'), ('ms', 'Malay'),
                            ('mt', 'Maltese'), ('mn', 'Mongolian'),
                            ('na', 'Nauru'), ('nv', 'Navajo; Navaho'),
                            ('nr', 'Ndebele, South; South Ndebele'),
                            ('nd', 'Ndebele, North; North Ndebele'),
                            ('ne', 'Nepali'),
                            ('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
                            ('nb', 'Bokmål, Norwegian; Norwegian Bokmål'),
                            ('no', 'Norwegian'), ('oc', 'Occitan (post 1500)'),
                            ('oj', 'Ojibwa'), ('or', 'Oriya'), ('om', 'Oromo'),
                            ('os', 'Ossetian')
                        ],
                        max_length=3
                    )
                ),
                (
                    'genre',
                    models.CharField(
                        choices=[
                            ('action', 'Action'), ('adventure', 'Adventure'),
                            ('fantasy', 'Fantasy'), ('horror', 'Horror'),
                            ('mystery', 'Mystery'), ('romance', 'Romance'),
                            ('science_fiction', 'Science Fiction'),
                            ('thriller', 'Thriller'), ('western', 'Western'),
                            ('biography', 'Biography'),
                            ('autobiography', 'Autobiography'),
                            ('comics', 'Comics'), ('cookbook', 'Cookbook'),
                            ('diary', 'Diary'), ('dictionary', 'Dictionary'),
                            ('encyclopedia', 'Encyclopedia'),
                            ('guide', 'Guide'), ('health', 'Health'),
                            ('history', 'History'), ('journal', 'Journal'),
                            ('math', 'Math'), ('memoir', 'Memoir'),
                            ('prayer', 'Prayer'), ('religion', 'Religion'),
                            ('textbook', 'Textbook'), ('poetry', 'Poetry'),
                            ('play', 'Play'), ('satire', 'Satire'),
                            ('science', 'Science'), ('travel', 'Travel'),
                            ('true_crime', 'True Crime')
                        ],
                        max_length=20
                    )
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='books',
                        related_query_name='book',
                        to='books.author'
                    )
                ),
                (
                    'publisher',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='books',
                        related_query_name='book',
                        to='books.publisher'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
