# Generated by Django 5.0.3 on 2024-03-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre'),
        (
            'books',
            '0003_author_deleted_book_deleted_publisher_deleted_and_more'
        ),
    ]

    operations = []  # type: ignore
