from django.db import models


class GenreChoices(models.TextChoices):
    ACTION = 'action', 'Action'
    ADVENTURE = 'adventure', 'Adventure'
    FANTASY = 'fantasy', 'Fantasy'
    HORROR = 'horror', 'Horror'
    MYSTERY = 'mystery', 'Mystery'
    ROMANCE = 'romance', 'Romance'
    SCIENCE_FICTION = 'science_fiction', 'Science Fiction'
    THRILLER = 'thriller', 'Thriller'
    WESTERN = 'western', 'Western'
    BIOGRAPHY = 'biography', 'Biography'
    AUTOBIOGRAPHY = 'autobiography', 'Autobiography'
    COMICS = 'comics', 'Comics'
    COOKBOOK = 'cookbook', 'Cookbook'
    DIARY = 'diary', 'Diary'
    DICTIONARY = 'dictionary', 'Dictionary'
    ENCYCLOPEDIA = 'encyclopedia', 'Encyclopedia'
    GUIDE = 'guide', 'Guide'
    HEALTH = 'health', 'Health'
    HISTORY = 'history', 'History'
    JOURNAL = 'journal', 'Journal'
    MATH = 'math', 'Math'
    MEMOIR = 'memoir', 'Memoir'
    PRAYER = 'prayer', 'Prayer'
    RELIGION = 'religion', 'Religion'
    TEXTBOOK = 'textbook', 'Textbook'
    POETRY = 'poetry', 'Poetry'
    PLAY = 'play', 'Play'
    SATIRE = 'satire', 'Satire'
    SCIENCE = 'science', 'Science'
    TRAVEL = 'travel', 'Travel'
    TRUE_CRIME = 'true_crime', 'True Crime'
