# Generated by Django 5.0.3 on 2024-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name='DashboardPermissions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
            ],
            options={
                'permissions': (('view_dashboard', 'Can view dashboard'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
