# Generated by Django 5.0.3 on 2024-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='email address'
            ),
        ),
    ]
