# Generated by Django 5.0.3 on 2024-04-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={
                'permissions':
                    (('view_own_address', 'Can view own address'),
                     ('change_own_address', 'Can change own address')),
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses'
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'permissions': (('view_profile', 'Can view profile'),
                                ('change_own_profile', 'Can change profile'))
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
    ]
