# Generated by Django 5.0.3 on 2024-04-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={
                'permissions':
                    (('add_own_address', 'Can add own address'),
                     ('view_own_address', 'Can view own address'),
                     ('change_own_address', 'Can change own address')),
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses'
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'permissions':
                    (('view_profile', 'Can view profile'),
                     ('change_own_profile', 'Can change own profile'))
            },
        ),
    ]
