# Generated by Django 5.0.3 on 2024-03-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
