# Generated by Django 5.0.4 on 2024-04-15 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'book_review',
            '0003_alter_review_books_alter_review_comments_and_more'
        ),
        (
            'books',
            '0005_alter_author_created_at_alter_author_deleted_and_more'
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='books',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                related_query_name='review',
                to='books.book',
                verbose_name='book'
            ),
        ),
    ]
