# Generated by Django 5.0.3 on 2024-04-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0004_alter_review_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={
                'permissions': (('add_own_review', 'Can add own review'),
                                ('change_own_review', 'Can change own review'),
                                ('delete_own_review', 'Can delete own review'))
            },
        ),
    ]
