# Generated by Django 5.0.3 on 2024-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'),
                         ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'),
                         ('CANCELLED', 'Cancelled')],
                default='PENDING',
                max_length=20
            ),
        ),
    ]
