# Generated by Django 5.0.3 on 2024-03-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                verbose_name=models.CharField(
                    choices=[('PENDING',
                              'Pending'), ('PROCESSING', 'Processing'),
                             ('CONFIRMED',
                              'Confirmed'), ('SHIPPED', 'Shipped'),
                             ('DELIVERED',
                              'Delivered'), ('CANCELLED', 'Cancelled')],
                    default='PENDING',
                    max_length=20
                )
            ),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'transaction_id',
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False
                    )
                ),
                (
                    'bank_tran_id',
                    models.CharField(blank=True, max_length=50, null=True)
                ),
                (
                    'amount',
                    models.DecimalField(decimal_places=2, max_digits=10)
                ),
                (
                    'store_amount',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    )
                ),
                ('currency', models.CharField(max_length=5)),
                (
                    'status',
                    models.CharField(
                        choices=[('PENDING', 'Pending'),
                                 ('SUCCESS', 'Success'), ('FAILED', 'Failed'),
                                 ('CANCELLED', 'Cancelled')],
                        max_length=10
                    )
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='shopping.order'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
