# Generated by Django 5.0.3 on 2024-03-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'shopping',
            '0005_orderbook_out_of_stock_alter_order_status_and_more'
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'),
                         ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'),
                         ('DELIVERED', 'Delivered'),
                         ('CANCELLED', 'Cancelled')],
                default='PENDING',
                max_length=20
            ),
        ),
    ]
