# Generated by Django 5.0.3 on 2024-03-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_alter_transaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='shopping.order'
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'),
                         ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')],
                max_length=10
            ),
        ),
    ]
