# Generated by Django 5.0.3 on 2024-03-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_order_deleted_orderbook_deleted'),
        ('shopping', '0010_alter_transaction_order_alter_transaction_status'),
    ]

    operations = []  # type: ignore
