# Generated by Django 5.0.3 on 2024-03-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_merge_20240319_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction',
                related_query_name='transaction',
                to='shopping.order'
            ),
        ),
    ]
