# Generated by Django 5.0.4 on 2024-04-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_alter_order_address_alter_order_books_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                related_query_name='order',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user'
            ),
        ),
    ]
