# Generated by Django 5.0.3 on 2024-04-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={
                'permissions': (('view_own_order', 'Can view own order'),
                                ('place_order', 'Can place order'))
            },
        ),
    ]
